# Gvisual mod navbar colors
PRODUCT_PACKAGES += \
    NavbarColorAmberOverlay \
    NavbarColorAmethystOverlay \
    NavbarColorAquamarineOverlay \
    NavbarColorAzureRadiance \
    NavbarColorBlackOverlay \
    NavbarColorBlueOverlay \
    NavbarColorBlueGreyOverlay \
    NavbarColorBrownOverlay \
    NavbarColorCarbonOverlay \
    NavbarColorCinnamonOverlay \
    NavbarColorCyanOverlay \
    NavbarColorDeepOrangeOverlay \
    NavbarColorDeepPurpleOverlay \
    NavbarColorGreenOverlay \
    NavbarColorGreyOverlay \
    NavbarColorIndigoOverlay \
    NavbarColorLightBlueOverlay \
    NavbarColorLightGreenOverlay \
    NavbarColorLimeOverlay \
    NavbarColorOceanOverlay \
    NavbarColorOrangeOverlay \
    NavbarColorOrchidOverlay \
    NavbarColorPaletteOverlay \
    NavbarColorPinkOverlay \
    NavbarColorPurpleOverlay \
    NavbarColorRedOverlay \
    NavbarColorSandOverlay \
    NavbarColorSpaceOverlay \
    NavbarColorTangerineOverlay \
    NavbarColorTealOverlay \
    NavbarColorYellowOverlay \
    NavbarColorAndroidOneGreenOverlay \
    NavbarColorCocaColaRedOverlay \
    NavbarColorDiscordPurpleOverlay \
    NavbarColorFacebookBlueOverlay \
    NavbarColorInstagramCeriseOverlay \
    NavbarColorJollibeeCrimsonOverlay \
    NavbarColorMonsterEnergyGreenOverlay \
    NavbarColorNextbitMintOverlay \
    NavbarColorOneplusRedOverlay \
    NavbarColorPepsiBlueOverlay \
    NavbarColorPocophoneYellowOverlay \
    NavbarColorRazerGreenOverlay \
    NavbarColorSamsungBlueOverlay \
    NavbarColorSpotifyGreenOverlay \
    NavbarColorStarbucksGreenOverlay \
    NavbarColorTwitchPurpleOverlay \
    NavbarColorTwitterBlueOverlay \
    NavbarColorXboxGreenOverlay \
    NavbarColorXiaomiOrangeOverlay
